version: '3.7'
services:
  as-readiness:
    build:
      context: readiness-api-service
      dockerfile: Dockerfile
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "as-readiness"
      public:
    ports:    
      - "3002:3002"   

  as-nginx:
    build:
      context: readiness-server
      dockerfile: Dockerfile
    depends_on:
      - "as-readiness"   
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "as-nginx"
      public:
    ports:    
      - "8080:80"  
    volumes:
      - ./readiness-server/html:/usr/local/openresty/nginx/html
      - ./readiness-server/templates:/usr/local/openresty/nginx/templates
      - ./readiness-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf 
      - ./readiness-server/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # this differs from a normal -v folder mount to maintaine with/out traefik 

networks:
  # everything that is *only* on "internal network" cannot talk to WAN
  private:
    internal: true
  # add this network to a container to make it talk to the rest of the world
  public: